#
# Copyright IBM Corp All Rights Reserved
#
# SPDX-License-Identifier: Apache-2.0
#
version: '3'

services:
  gremlin:
    image: bricaud/gremlin-server-with-demo-graph
    ports:
      - "8182:8182"
      
  graphexp:
    image: joov/graphexp:0.1
    build:
      context: ./graphexp
      args:
        http_proxy: ${http_proxy}
        https_proxy: ${https_proxy}
        no_proxy: ${no_proxy}
    ports:
      - "8183:80"
    depends_on:
      - gremlin


