#
# Copyright IBM Corp All Rights Reserved
#
# SPDX-License-Identifier: Apache-2.0
#
version: '3'

networks:
  basic:
 
services:
  gremlin:
    image: bricaud/gremlin-server-with-demo-graph
    ports:
      - "8182:8182"
    networks:
      - basic
      
  graphexp:
    build:
      context: ./graphexp
      args:
        http_proxy: ${http_proxy}
        https_proxy: ${https_proxy}
        no_proxy: ${no_proxy}
    ports:
      - "8183:8183"
    networks:
      - basic


